[env]
platform = espressif32@6.9.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:receiver]
src_filter = +<receiver.cpp>

[env:team_red]
src_filter = +<buzzer.cpp>
build_flags =
  ${env.build_flags}
  -DTEAM_ID=1

[env:team_green]
src_filter = +<buzzer.cpp>
build_flags =
  ${env.build_flags}
  -DTEAM_ID=2

[env:team_blue]
src_filter = +<buzzer.cpp>
build_flags =
  ${env.build_flags}
  -DTEAM_ID=3

[env:team_yellow]
src_filter = +<buzzer.cpp>
build_flags =
  ${env.build_flags}
  -DTEAM_ID=4
